// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int loopcounter_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int loopcounter = 10;
	public class Write
	{
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int loopcounter_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int loopcounter = 110;
		/// <summary>PID: 1010 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int countup_1010 = 1010;
		/// <summary>PID: 1010 | Type: write</summary>
		public const int countup = 1010;
		/// <summary>PID: 1020 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int countdown_1020 = 1020;
		/// <summary>PID: 1020 | Type: write</summary>
		public const int countdown = 1020;
	}
}
public class WriteParameters
{
	/// <summary>PID: 110  | Type: write</summary>
	public System.Object Loopcounter {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 1010  | Type: write | DISCREETS: Up = 1</summary>
	public System.Object Countup {get { return Protocol.GetParameter(1010); }set { Protocol.SetParameter(1010, value); }}
	/// <summary>PID: 1020  | Type: write | DISCREETS: Down = 2</summary>
	public System.Object Countdown {get { return Protocol.GetParameter(1020); }set { Protocol.SetParameter(1020, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Loopcounter_10 { get; set; }
	object Loopcounter { get; set; }
	object Loopcounter_110 { get; set; }
	object Countup_1010 { get; set; }
	object Countup { get; set; }
	object Countdown_1020 { get; set; }
	object Countdown { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Loopcounter_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Loopcounter {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Loopcounter_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 1010  | Type: write | DISCREETS: Up = 1</summary>
	public System.Object Countup_1010 {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1010  | Type: write | DISCREETS: Up = 1</summary>
	public System.Object Countup {get { return Write.Countup; }set { Write.Countup = value; }}
	/// <summary>PID: 1020  | Type: write | DISCREETS: Down = 2</summary>
	public System.Object Countdown_1020 {get { return GetParameter(1020); }set { SetParameter(1020, value); }}
	/// <summary>PID: 1020  | Type: write | DISCREETS: Down = 2</summary>
	public System.Object Countdown {get { return Write.Countdown; }set { Write.Countdown = value; }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
